# Generated by Django 5.2.3 on 2026-07-31 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyExecutiveDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Numéro de semaine')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('overall_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='État général')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement global (%)')),
                ('planning_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='Planning')),
                ('budget_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='Budget')),
                ('quality_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='Qualité')),
                ('platform_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='Plateforme')),
                ('user_satisfaction_status', models.CharField(choices=[('GREEN', 'Vert — Conforme'), ('YELLOW', 'Jaune — Vigilance'), ('RED', 'Rouge — Critique')], default='GREEN', max_length=10, verbose_name='Satisfaction des utilisateurs')),
                ('accounts_created', models.PositiveIntegerField(default=0, verbose_name='Comptes créés')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Utilisateurs actifs')),
                ('groups_created', models.PositiveIntegerField(default=0, verbose_name='Groupes créés')),
                ('registered_members', models.PositiveIntegerField(default=0, verbose_name='Membres inscrits')),
                ('contributions_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de cotisations')),
                ('contributions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant des cotisations')),
                ('savings_deposits_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de dépôts d’épargne')),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total de l’épargne')),
                ('credits_granted_count', models.PositiveIntegerField(default=0, verbose_name='Crédits accordés')),
                ('credits_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total des crédits')),
                ('repayments_count', models.PositiveIntegerField(default=0, verbose_name='Remboursements réalisés')),
                ('investments_count', models.PositiveIntegerField(default=0, verbose_name='Projets d’investissement')),
                ('investments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total investi')),
                ('platform_availability', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disponibilité de la plateforme (%)')),
                ('successful_transaction_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de réussite des transactions (%)')),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Temps moyen de réponse (secondes)')),
                ('critical_incidents', models.PositiveIntegerField(default=0, verbose_name='Incidents critiques')),
                ('highlights', models.TextField(blank=True, verbose_name='Faits marquants')),
                ('achievements', models.TextField(blank=True, verbose_name='Réalisations majeures')),
                ('difficulties', models.TextField(blank=True, verbose_name='Difficultés rencontrées')),
                ('opportunities', models.TextField(blank=True, verbose_name='Opportunités identifiées')),
                ('major_risks', models.TextField(blank=True, verbose_name='Risques majeurs')),
                ('expected_decisions', models.TextField(blank=True, verbose_name='Décisions attendues')),
                ('next_week_priorities', models.TextField(blank=True, verbose_name='Priorités de la semaine suivante')),
                ('project_manager_comment', models.TextField(blank=True, verbose_name='Commentaire du chef de projet')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_executive_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Tableau de bord exécutif',
                'verbose_name_plural': 'Tableaux de bord exécutifs',
                'ordering': ['-period_end', '-week_number'],
                'permissions': [('access_executive_dashboard', 'Peut accéder au tableau de bord exécutif')],
                'constraints': [models.UniqueConstraint(fields=('week_number', 'period_start', 'period_end'), name='unique_executive_dashboard_period')],
            },
        ),
    ]
