# Generated by Django 5.2.3 on 2026-08-06 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisationtontine', '0004_remove_groupmember_unique_member_per_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='versement',
            name='cotisationt_statut_cc8646_idx',
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_customer_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_invoice_url',
            field=models.URLField(blank=True, help_text='Adresse de la page de paiement PayDunya', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_paid_at',
            field=models.DateTimeField(blank=True, help_text='Date de confirmation du paiement PayDunya', null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_payload',
            field=models.JSONField(blank=True, help_text='Dernière réponse PayDunya conservée pour audit et rapprochement', null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_receipt_url',
            field=models.URLField(blank=True, help_text='Adresse du reçu électronique PayDunya', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], db_index=True, help_text='Statut transmis par PayDunya', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_token',
            field=models.CharField(blank=True, help_text='Token unique de la facture PayDunya', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(choices=[('WAVE', 'Wave'), ('OM', 'Orange Money'), ('CAISSE', 'Caisse'), ('PAYDUNYA', 'PayDunya')], default='WAVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'cycle', 'tour', 'statut'], name='cotisationt_member__1065f4_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['methode', 'statut'], name='cotisationt_methode_9c8203_idx'),
        ),
    ]
