# Generated by Django 5.2.3 on 2026-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0003_remove_versement_preuve_alter_versement_methode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretdemande',
            name='penalite',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Pénalité (%)'),
        ),
    ]
