# Generated by Django 5.2.11 on 2026-08-06 23:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epargnecredit', '0004_pretdemande_penalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='frais',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='paydunya_invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='paydunya_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='paydunya_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pretremboursement',
            name='paydunya_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='paydunya_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pretdemande',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé'), ('CLOSED', 'Soldé')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='pretremboursement',
            name='methode',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('MANUEL', 'Manuel'), ('PAYDUNYA', 'PayDunya')], default='CAISSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pretremboursement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pretremboursement',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='versement',
            name='methode',
            field=models.CharField(choices=[('CAISSE', 'Caisse'), ('MANUEL', 'Manuel'), ('PAYDUNYA', 'PayDunya')], default='CAISSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='pretremboursement',
            index=models.Index(fields=['pret', 'statut'], name='ec_remb_pret_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='pretremboursement',
            index=models.Index(fields=['methode', 'statut'], name='ec_remb_method_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['member', 'statut'], name='ec_vers_member_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='versement',
            index=models.Index(fields=['methode', 'statut'], name='ec_vers_method_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_epargnecredit_group_member'),
        ),
    ]
