# Generated by Django 5.2.3 on 2026-08-02 01:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('community_investment', '0002_communityimpact_dividenddeclaration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('code', models.CharField(max_length=60, verbose_name="Code de l'étape")),
                ('name', models.CharField(max_length=180, verbose_name="Nom de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('stage_type', models.CharField(choices=[('AUTOMATED', 'Traitement automatique'), ('REVIEW', 'Instruction'), ('APPROVAL', 'Approbation'), ('COMMITTEE', 'Comité'), ('LEGAL', 'Structuration juridique'), ('EXECUTION', 'Exécution'), ('AUDIT', 'Audit et contrôle'), ('FINANCIAL', 'Traitement financier'), ('CLOSURE', 'Clôture'), ('OTHER', 'Autre')], default='REVIEW', max_length=20, verbose_name="Type d'étape")),
                ('order', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Étape initiale')),
                ('is_final', models.BooleanField(default=False, verbose_name='Étape finale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Étape active')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Étape obligatoire')),
                ('requires_decision', models.BooleanField(default=True, verbose_name='Décision requise')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='Commentaire obligatoire')),
                ('requires_document', models.BooleanField(default=False, verbose_name='Document obligatoire')),
                ('target_duration_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai cible en jours')),
                ('escalation_after_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Escalade après un nombre de jours')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('responsible_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_stages', to='auth.group', verbose_name='Groupe responsable')),
            ],
            options={
                'verbose_name': 'Étape de gouvernance',
                'verbose_name_plural': 'Étapes de gouvernance',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, verbose_name='Code du workflow')),
                ('name', models.CharField(max_length=180, verbose_name='Nom du workflow')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Version')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('is_default', models.BooleanField(default=False, help_text="Ce workflow sera utilisé par défaut lors de la création d'un nouveau dossier d'investissement.", verbose_name='Workflow par défaut')),
                ('allow_parallel_tasks', models.BooleanField(default=True, verbose_name='Autoriser les tâches parallèles')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Activé le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Workflow de gouvernance',
                'verbose_name_plural': 'Workflows de gouvernance',
                'ordering': ['code', '-version'],
                'permissions': [('manage_governance_workflows', 'Peut gérer les workflows de gouvernance'), ('view_governance_dashboard', 'Peut consulter le tableau de bord de gouvernance')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(max_length=180, verbose_name='Nom de la transition')),
                ('code', models.CharField(max_length=60, verbose_name='Code de la transition')),
                ('trigger', models.CharField(choices=[('APPROVE', 'Approuver'), ('REJECT', 'Rejeter'), ('REQUEST_INFO', 'Demander des informations complémentaires'), ('RETURN', "Retourner à l'étape précédente"), ('SUBMIT', 'Soumettre'), ('COMPLETE', 'Terminer'), ('SUSPEND', 'Suspendre'), ('RESUME', 'Reprendre'), ('AUTOMATIC', 'Transition automatique'), ('CANCEL', 'Annuler')], max_length=20, verbose_name='Action déclenchante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Transition active')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='Commentaire obligatoire')),
                ('requires_document', models.BooleanField(default=False, verbose_name='Document obligatoire')),
                ('requires_permission', models.CharField(blank=True, help_text="Exemple : governance.approve_governance_decision. Laisser vide si aucune permission spécifique n'est requise.", max_length=150, verbose_name='Permission Django requise')),
                ('minimum_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score minimal nécessaire pour autoriser cette transition.', max_digits=5, null=True, verbose_name='Score minimal requis')),
                ('condition_description', models.TextField(blank=True, verbose_name='Description des conditions')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='governance.governancestage', verbose_name='Étape de départ')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='governance.governancestage', verbose_name="Étape d'arrivée")),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='governance.governanceworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Transition de gouvernance',
                'verbose_name_plural': 'Transitions de gouvernance',
                'ordering': ['workflow', 'from_stage__order', 'to_stage__order'],
            },
        ),
        migrations.AddField(
            model_name='governancestage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='governance.governanceworkflow', verbose_name='Workflow'),
        ),
        migrations.CreateModel(
            name='GovernanceInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarré'), ('ACTIVE', 'En cours'), ('WAITING', 'En attente'), ('SUSPENDED', 'Suspendu'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='NOT_STARTED', max_length=20, verbose_name='Statut')),
                ('governance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score de gouvernance (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('stage_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Étape actuelle démarrée le')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name="Échéance de l'étape actuelle")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspendu le')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Motif de suspension')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('last_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière action le')),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_governance_instances', to=settings.AUTH_USER_MODEL, verbose_name='Dernière action réalisée par')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_instance', to='community_investment.communityinvestmentproject', verbose_name="Projet d'investissement")),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_governance_instances', to=settings.AUTH_USER_MODEL, verbose_name='Démarré par')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_instances', to='governance.governancestage', verbose_name='Étape actuelle')),
                ('previous_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_instances', to='governance.governancestage', verbose_name='Étape précédente')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='governance.governanceworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Instance de gouvernance',
                'verbose_name_plural': 'Instances de gouvernance',
                'ordering': ['-created_at'],
                'permissions': [('review_governance_case', 'Peut instruire un dossier de gouvernance'), ('approve_governance_decision', 'Peut approuver une décision de gouvernance'), ('audit_governance_case', 'Peut auditer un dossier de gouvernance')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('task_type', models.CharField(choices=[('REVIEW', 'Instruction'), ('VALIDATION', 'Validation'), ('DOCUMENT', 'Collecte ou contrôle documentaire'), ('ANALYSIS', 'Analyse'), ('VOTE', 'Vote'), ('SIGNATURE', 'Signature'), ('AUDIT', 'Audit'), ('FOLLOW_UP', 'Suivi'), ('CORRECTIVE_ACTION', 'Action corrective'), ('OTHER', 'Autre')], default='REVIEW', max_length=30, verbose_name='Type de tâche')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente'), ('CRITICAL', 'Critique')], default='NORMAL', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('PENDING', 'À traiter'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('WAITING', 'En attente'), ('COMPLETED', 'Terminée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assignée le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commencée le')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Échéance')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('completion_comment', models.TextField(blank=True, verbose_name='Commentaire de traitement')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text="Permet d'enregistrer des résultats techniques ou des données calculées au format JSON.", verbose_name='Résultat structuré')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Tâche obligatoire')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignée par')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_governance_tasks', to='auth.group', verbose_name='Groupe assigné')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_governance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_governance_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Terminée par')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='governance.governanceinstance', verbose_name='Instance de gouvernance')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='governance.governancestage', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Tâche de gouvernance',
                'verbose_name_plural': 'Tâches de gouvernance',
                'ordering': ['due_at', '-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='gov_task_status_idx'), models.Index(fields=['assigned_to', 'status'], name='gov_task_user_idx'), models.Index(fields=['assigned_group', 'status'], name='gov_task_group_idx'), models.Index(fields=['due_at', 'status'], name='gov_task_due_idx'), models.Index(fields=['instance', 'stage', 'status'], name='gov_task_instance_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='governanceworkflow',
            index=models.Index(fields=['status', 'is_default'], name='gov_workflow_status_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceworkflow',
            index=models.Index(fields=['code', 'version'], name='gov_workflow_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='governanceworkflow',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='gov_unique_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='governanceworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='gov_only_one_default_workflow'),
        ),
        migrations.AddIndex(
            model_name='governancetransition',
            index=models.Index(fields=['workflow', 'is_active'], name='gov_transition_active_idx'),
        ),
        migrations.AddIndex(
            model_name='governancetransition',
            index=models.Index(fields=['from_stage', 'trigger'], name='gov_transition_trigger_idx'),
        ),
        migrations.AddConstraint(
            model_name='governancetransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='gov_unique_transition_code'),
        ),
        migrations.AddConstraint(
            model_name='governancetransition',
            constraint=models.UniqueConstraint(fields=('from_stage', 'to_stage', 'trigger'), name='gov_unique_stage_transition'),
        ),
        migrations.AddConstraint(
            model_name='governancetransition',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_score__isnull', True), models.Q(('minimum_score__gte', 0), ('minimum_score__lte', 100)), _connector='OR'), name='gov_transition_score_valid'),
        ),
        migrations.AddIndex(
            model_name='governancestage',
            index=models.Index(fields=['workflow', 'order', 'is_active'], name='gov_stage_order_idx'),
        ),
        migrations.AddIndex(
            model_name='governancestage',
            index=models.Index(fields=['stage_type', 'is_active'], name='gov_stage_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='governancestage',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='gov_unique_stage_code'),
        ),
        migrations.AddConstraint(
            model_name='governancestage',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='gov_unique_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='governancestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow',), name='gov_one_initial_stage'),
        ),
        migrations.AddIndex(
            model_name='governanceinstance',
            index=models.Index(fields=['status', 'current_stage'], name='gov_instance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceinstance',
            index=models.Index(fields=['workflow', 'status'], name='gov_instance_workflow_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceinstance',
            index=models.Index(fields=['due_at', 'status'], name='gov_instance_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='governanceinstance',
            constraint=models.CheckConstraint(condition=models.Q(('governance_score__gte', 0), ('governance_score__lte', 100)), name='gov_instance_score_valid'),
        ),
    ]
