# Generated by Django 5.2.3 on 2026-08-02 18:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_investment', '0002_communityimpact_dividenddeclaration_and_more'),
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceDecisionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=60, unique=True, verbose_name='Référence')),
                ('decision_code', models.CharField(choices=[('APPROVE', 'Approuver'), ('REJECT', 'Rejeter'), ('REQUEST_INFO', 'Demander des informations complémentaires'), ('ADVANCE', "Passer à l'étape suivante"), ('BLOCK', 'Bloquer'), ('MANUAL_REVIEW', 'Soumettre à une revue humaine')], max_length=30, verbose_name='Décision')),
                ('application_status', models.CharField(choices=[('RECOMMENDED', 'Recommandation uniquement'), ('APPLIED', 'Décision appliquée'), ('NOT_APPLIED', 'Décision non appliquée'), ('OVERRIDDEN', 'Décision remplacée manuellement'), ('FAILED', "Échec lors de l'application")], default='RECOMMENDED', max_length=20, verbose_name="Statut d'application")),
                ('global_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score global (%)')),
                ('eligible', models.BooleanField(default=False, verbose_name='Dossier éligible')),
                ('can_advance', models.BooleanField(default=False, verbose_name='Peut avancer')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé de la décision')),
                ('criteria_snapshot', models.JSONField(blank=True, default=list, verbose_name='Critères évalués')),
                ('blocking_reasons', models.JSONField(blank=True, default=list, verbose_name='Motifs bloquants')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Avertissements')),
                ('engine_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Instantané complet du moteur')),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Évalué le')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Appliqué le')),
                ('override_reason', models.TextField(blank=True, verbose_name='Motif du remplacement manuel')),
                ('failure_message', models.TextField(blank=True, verbose_name="Message d'échec")),
                ('actor_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('actor_user_agent', models.TextField(blank=True, verbose_name='Navigateur ou client')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_decision_logs', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_decision_logs', to='governance.governancestage', verbose_name='Étape de départ')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='governance.governanceinstance', verbose_name='Instance de gouvernance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_decision_logs', to='community_investment.communityinvestmentproject', verbose_name='Projet')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_decision_logs', to='governance.governancestage', verbose_name="Étape d'arrivée")),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='governance.governancetransition', verbose_name='Transition utilisée')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='governance.governanceworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Journal de décision',
                'verbose_name_plural': 'Journaux des décisions',
                'ordering': ['-evaluated_at', '-created_at'],
                'permissions': [('view_governance_audit_log', "Peut consulter le journal d'audit de gouvernance"), ('override_governance_decision', 'Peut remplacer une décision du moteur')],
                'indexes': [models.Index(fields=['instance', 'evaluated_at'], name='gov_log_instance_idx'), models.Index(fields=['project', 'decision_code'], name='gov_log_project_idx'), models.Index(fields=['application_status', 'evaluated_at'], name='gov_log_status_idx'), models.Index(fields=['workflow', 'from_stage', 'to_stage'], name='gov_log_transition_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('global_score__gte', 0), ('global_score__lte', 100)), name='gov_log_score_valid')],
            },
        ),
    ]
