# Generated by Django 5.2.3 on 2026-08-01 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epargnecredit', '0004_pretdemande_penalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentEligibilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Politique standard d'investissement communautaire", max_length=180, unique=True, verbose_name='Nom de la politique')),
                ('minimum_capital', models.DecimalField(decimal_places=2, default=Decimal('30000000.00'), help_text='Seuil minimal de capitalisation du groupe. Valeur initiale : 30 000 000 FCFA.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capital minimum requis')),
                ('minimum_group_age_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)], verbose_name='Ancienneté minimale du groupe en mois')),
                ('minimum_active_members', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre minimal de membres actifs')),
                ('minimum_repayment_rate', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux minimal de remboursement (%)')),
                ('maximum_overdue_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name="Taux maximal d'impayés (%)")),
                ('requires_audited_accounts', models.BooleanField(default=False, verbose_name='Comptes financiers vérifiés requis')),
                ('requires_group_approval', models.BooleanField(default=True, verbose_name='Validation formelle du groupe requise')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'entrée en vigueur")),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name="Date de fin d'application")),
                ('is_active', models.BooleanField(default=True, verbose_name='Politique active')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investment_policies', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': "Politique d'éligibilité",
                'verbose_name_plural': "Politiques d'éligibilité",
                'ordering': ['-is_active', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PostalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nom du bureau')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Code du bureau')),
                ('city', models.CharField(max_length=120, verbose_name='Ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse électronique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bureau actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='authorized_postal_offices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs autorisés')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_postal_offices', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du bureau')),
            ],
            options={
                'verbose_name': 'Bureau de poste',
                'verbose_name_plural': 'Bureaux de poste',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityInvestmentProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('sector', models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('LIVESTOCK', 'Élevage'), ('FISHING', 'Pêche et aquaculture'), ('TRADE', 'Commerce'), ('CRAFTS', 'Artisanat'), ('INDUSTRY', 'Transformation et industrie'), ('REAL_ESTATE', 'Immobilier'), ('ENERGY', 'Énergie'), ('TRANSPORT', 'Transport et logistique'), ('DIGITAL', 'Numérique'), ('TOURISM', 'Tourisme'), ('HEALTH', 'Santé'), ('EDUCATION', 'Éducation et formation'), ('ENVIRONMENT', 'Environnement'), ('OTHER', 'Autre')], max_length=30, verbose_name="Secteur d'activité")),
                ('project_location', models.CharField(blank=True, max_length=255, verbose_name='Localisation du projet')),
                ('capital_at_submission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Capital du groupe à la soumission')),
                ('threshold_at_submission', models.DecimalField(decimal_places=2, default=Decimal('30000000.00'), editable=False, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Seuil applicable à la soumission')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant demandé')),
                ('community_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Apport communautaire')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant approuvé')),
                ('mobilized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant mobilisé')),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant décaissé')),
                ('expected_return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rendement annuel attendu (%)')),
                ('expected_jobs', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emplois prévus")),
                ('expected_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Nombre de bénéficiaires prévus')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis au bureau de poste'), ('OFFICE_REVIEW', 'Examen par le bureau'), ('ADDITIONAL_INFO', 'Informations complémentaires requises'), ('REGIONAL_REVIEW', 'Examen régional'), ('CENTRAL_REVIEW', 'Instruction par la Direction des investissements'), ('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('FINANCING', 'Financement en mobilisation'), ('IN_PROGRESS', "En cours d'exécution"), ('SUSPENDED', 'Suspendu'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=30, verbose_name='Statut du projet')),
                ('eligibility_status', models.CharField(choices=[('PENDING', 'À évaluer'), ('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('OVERRIDDEN', 'Dérogation approuvée')], default='PENDING', max_length=20, verbose_name="Statut d'éligibilité")),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MODERATE', 'Modéré'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MODERATE', max_length=20, verbose_name='Niveau de risque')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name="Taux d'avancement (%)")),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Date de démarrage prévue')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Date de démarrage réelle')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décision prise le')),
                ('eligibility_override_reason', models.TextField(blank=True, verbose_name='Motif de dérogation')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du rejet')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_community_investment_projects', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_investment_projects', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_investment_projects', to='epargnecredit.group', verbose_name="Groupe d'épargne-crédit")),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_community_investment_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du projet')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_investment_projects', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par')),
                ('eligibility_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='community_investment.investmenteligibilitypolicy', verbose_name="Politique d'éligibilité appliquée")),
                ('postal_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_investment_projects', to='community_investment.postaloffice', verbose_name='Bureau de poste accompagnateur')),
            ],
            options={
                'verbose_name': "Projet d'investissement communautaire",
                'verbose_name_plural': "Projets d'investissement communautaire",
                'ordering': ['-created_at'],
                'permissions': [('manage_community_investments', 'Peut gérer les investissements communautaires'), ('review_community_investment', "Peut instruire un projet d'investissement"), ('approve_community_investment', "Peut approuver un projet d'investissement"), ('view_national_investment_dashboard', 'Peut consulter le tableau de bord national'), ('view_project_financial_data', 'Peut consulter les données financières des projets')],
            },
        ),
        migrations.CreateModel(
            name='PostalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(help_text='Exemple : DKR, THS, KOL.', max_length=30, unique=True, verbose_name='Code de la région')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Région active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_postal_regions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable régional')),
            ],
            options={
                'verbose_name': 'Région postale',
                'verbose_name_plural': 'Régions postales',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='postaloffice',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postal_offices', to='community_investment.postalregion', verbose_name='Région postale'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_capital__gt', 0)), name='ci_policy_minimum_capital_positive'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_repayment_rate__gte', 0), ('minimum_repayment_rate__lte', 100)), name='ci_policy_repayment_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_overdue_rate__gte', 0), ('maximum_overdue_rate__lte', 100)), name='ci_policy_overdue_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='ci_only_one_active_policy'),
        ),
        migrations.AddIndex(
            model_name='communityinvestmentproject',
            index=models.Index(fields=['status', 'risk_level'], name='ci_project_status_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvestmentproject',
            index=models.Index(fields=['postal_office', 'status'], name='ci_project_office_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvestmentproject',
            index=models.Index(fields=['group', 'status'], name='ci_project_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvestmentproject',
            index=models.Index(fields=['eligibility_status'], name='ci_project_eligibility_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvestmentproject',
            index=models.Index(fields=['created_at'], name='ci_project_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='ci_project_requested_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('community_contribution__gte', 0)), name='ci_project_contribution_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', 0)), name='ci_project_approved_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('mobilized_amount__gte', 0)), name='ci_project_mobilized_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('disbursed_amount__gte', 0)), name='ci_project_disbursed_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='ci_project_progress_valid'),
        ),
        migrations.AddIndex(
            model_name='postalregion',
            index=models.Index(fields=['code'], name='ci_region_code_idx'),
        ),
        migrations.AddIndex(
            model_name='postalregion',
            index=models.Index(fields=['is_active'], name='ci_region_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postaloffice',
            index=models.Index(fields=['region', 'is_active'], name='ci_office_region_idx'),
        ),
        migrations.AddIndex(
            model_name='postaloffice',
            index=models.Index(fields=['code'], name='ci_office_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='postaloffice',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='ci_unique_office_name_per_region'),
        ),
    ]
