# Generated by Django 5.2.3 on 2026-08-01 19:33

import community_investment.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_investment', '0001_initial'),
        ('epargnecredit', '0004_pretdemande_penalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('jobs_created', models.PositiveIntegerField(default=0, verbose_name='Emplois créés')),
                ('direct_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Bénéficiaires directs')),
                ('indirect_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Bénéficiaires indirects')),
                ('women_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Femmes bénéficiaires')),
                ('youth_beneficiaries', models.PositiveIntegerField(default=0, verbose_name='Jeunes bénéficiaires')),
                ('communities_impacted', models.PositiveIntegerField(default=0, verbose_name='Communautés ou localités touchées')),
                ('annual_income_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Revenus annuels générés')),
                ('assets_created_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Valeur des actifs créés')),
                ('environmental_benefits', models.TextField(blank=True, verbose_name='Bénéfices environnementaux')),
                ('social_benefits', models.TextField(blank=True, verbose_name='Bénéfices sociaux')),
                ('measurement_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de mesure')),
            ],
            options={
                'verbose_name': 'Impact communautaire',
                'verbose_name_plural': 'Impacts communautaires',
            },
        ),
        migrations.CreateModel(
            name='DividendDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('declared_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total déclaré')),
                ('declaration_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de déclaration')),
                ('planned_payment_date', models.DateField(blank=True, null=True, verbose_name='Date prévue de paiement')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('APPROVED', 'Approuvée'), ('PAYMENT_IN_PROGRESS', 'Paiement en cours'), ('PAID', 'Entièrement payée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=25, verbose_name='Statut')),
                ('resolution_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence de la décision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('ownership_percentage_snapshot', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Participation retenue (%)')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant brut')),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Retenues')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant net')),
            ],
            options={
                'verbose_name': 'Droit aux dividendes',
                'verbose_name_plural': 'Droits aux dividendes',
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(blank=True, max_length=60, verbose_name='Mode de paiement')),
                ('transaction_reference', models.CharField(blank=True, max_length=150, verbose_name='Référence de transaction')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('PAID', 'Payé'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberEconomicRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('contribution_reference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Contribution de référence')),
                ('economic_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Quote-part économique interne (%)')),
                ('dividend_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Droit interne aux dividendes (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Droit actif')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Applicable à partir du')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name="Applicable jusqu'au")),
            ],
            options={
                'verbose_name': "Droit économique d'un membre",
                'verbose_name_plural': 'Droits économiques des membres',
            },
        ),
        migrations.CreateModel(
            name='ProfitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('legal_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Réserve légale')),
                ('operating_reserve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Réserve d'exploitation")),
                ('maintenance_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Fonds de maintenance')),
                ('risk_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Fonds de sécurité')),
                ('reinvestment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Montant réinvesti')),
                ('distributable_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Bénéfice distribuable')),
                ('resolution_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence de la décision')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('contribution_type', models.CharField(choices=[('CASH', 'Apport financier'), ('LAND', 'Terrain'), ('BUILDING', 'Bâtiment'), ('EQUIPMENT', 'Équipement'), ('TECHNOLOGY', 'Technologie'), ('SOFTWARE', 'Plateforme ou logiciel'), ('INTELLECTUAL_PROPERTY', 'Propriété intellectuelle'), ('NETWORK', 'Réseau territorial ou commercial'), ('MANAGEMENT', 'Accompagnement et gestion'), ('EXPERTISE', 'Expertise technique'), ('OTHER', 'Autre apport')], max_length=30, verbose_name="Nature de l'apport")),
                ('description', models.TextField(verbose_name="Description de l'apport")),
                ('declared_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valeur déclarée')),
                ('recognized_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valeur reconnue')),
                ('valuation_method', models.CharField(blank=True, max_length=255, verbose_name='Méthode de valorisation')),
                ('valuation_report_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence du rapport de valorisation')),
                ('supporting_document', models.FileField(blank=True, upload_to=community_investment.models.contribution_document_upload_to, verbose_name='Document justificatif')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('UNDER_VALUATION', 'En évaluation'), ('RECOGNIZED', 'Apport reconnu'), ('REJECTED', 'Apport rejeté'), ('CANCELLED', 'Apport annulé')], default='PROPOSED', max_length=25, verbose_name='Statut')),
                ('contribution_date', models.DateField(blank=True, null=True, verbose_name="Date de l'apport")),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Apport au projet',
                'verbose_name_plural': 'Apports aux projets',
                'ordering': ['project', 'stakeholder', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('document_type', models.CharField(choices=[('BUSINESS_PLAN', "Plan d'affaires"), ('FEASIBILITY_STUDY', 'Étude de faisabilité'), ('RESOLUTION', 'Résolution du groupement'), ('STATUTES', 'Statuts'), ('INVESTMENT_AGREEMENT', "Convention d'investissement"), ('SHAREHOLDERS_AGREEMENT', "Pacte d'associés ou d'actionnaires"), ('VALUATION_REPORT', 'Rapport de valorisation'), ('CONTRACT', 'Contrat'), ('INVOICE', 'Facture'), ('FINANCIAL_REPORT', 'Rapport financier'), ('ACTIVITY_REPORT', "Rapport d'activité"), ('PHOTO', 'Photographie'), ('OTHER', 'Autre')], max_length=40, verbose_name='Type de document')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to=community_investment.models.project_document_upload_to, verbose_name='Fichier')),
                ('version', models.CharField(blank=True, max_length=30, verbose_name='Version')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Document validé')),
            ],
            options={
                'verbose_name': 'Document du projet',
                'verbose_name_plural': 'Documents des projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('category', models.CharField(choices=[('RAW_MATERIALS', 'Matières premières'), ('SALARIES', 'Salaires'), ('EQUIPMENT', 'Équipements'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('ENERGY', 'Énergie'), ('TAXES', 'Impôts et taxes'), ('MANAGEMENT', 'Frais de gestion'), ('TECHNOLOGY', 'Frais technologiques'), ('MARKETING', 'Marketing'), ('OTHER', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de la charge')),
                ('supporting_document', models.FileField(blank=True, upload_to=community_investment.models.project_document_upload_to, verbose_name='Justificatif')),
            ],
            options={
                'verbose_name': 'Charge du projet',
                'verbose_name_plural': 'Charges des projets',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeeAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('calculation_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Base de calcul')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant calculé')),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculé'), ('APPROVED', 'Approuvé'), ('PAID', 'Payé'), ('CANCELLED', 'Annulé')], default='CALCULATED', max_length=20, verbose_name='Statut')),
                ('payment_reference', models.CharField(blank=True, max_length=150, verbose_name='Référence de paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
            ],
            options={
                'verbose_name': 'Rémunération calculée',
                'verbose_name_plural': 'Rémunérations calculées',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('beneficiary_type', models.CharField(choices=[('POSTE', 'La Poste Sénégal'), ('YAAYESS', 'YAAYESS'), ('PARTNER', 'Partenaire'), ('PROJECT_DIRECTION', 'Direction des investissements communautaires')], max_length=30, verbose_name='Bénéficiaire')),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du bénéficiaire')),
                ('fee_type', models.CharField(choices=[('STRUCTURING', 'Frais de structuration'), ('MANAGEMENT', 'Frais de gestion'), ('TECHNOLOGY', 'Frais technologiques'), ('MONITORING', 'Frais de suivi territorial'), ('PERFORMANCE', 'Rémunération de performance'), ('TRANSACTION', 'Frais de transaction'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de rémunération')),
                ('calculation_method', models.CharField(choices=[('FIXED', 'Montant fixe'), ('REVENUE_PERCENTAGE', "Pourcentage du chiffre d'affaires"), ('PROFIT_PERCENTAGE', 'Pourcentage du bénéfice'), ('CAPITAL_PERCENTAGE', 'Pourcentage du capital')], max_length=30, verbose_name='Mode de calcul')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant fixe')),
                ('percentage_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux (%)')),
                ('annual_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plafond annuel')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Applicable à partir du')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name="Applicable jusqu'au")),
                ('agreement_reference', models.CharField(max_length=120, verbose_name='Référence de la convention')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('APPROVED', 'Approuvée'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue'), ('TERMINATED', 'Terminée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Règle de rémunération',
                'verbose_name_plural': 'Règles de rémunération',
                'ordering': ['project', 'beneficiary_type', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Chiffre d'affaires")),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Charges d'exploitation")),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Impôts et taxes')),
                ('depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Amortissements')),
                ('management_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name="Frais de gestion et d'accompagnement")),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Résultat net')),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total des actifs')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total des passifs')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Trésorerie')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VERIFIED', 'Vérifié'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'État financier du projet',
                'verbose_name_plural': 'États financiers des projets',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MODERATE', 'Modérée'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], default='MODERATE', max_length=20, verbose_name='Gravité')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('UNDER_REVIEW', 'En analyse'), ('CORRECTIVE_ACTION', 'Action corrective'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clos')], default='OPEN', max_length=25, verbose_name='Statut')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Action corrective')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Signalé le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
            ],
            options={
                'verbose_name': 'Incident du projet',
                'verbose_name_plural': 'Incidents des projets',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Dénomination sociale')),
                ('legal_form', models.CharField(choices=[('COOPERATIVE', 'Société coopérative'), ('SARL', 'SARL'), ('SAS', 'SAS'), ('SA', 'SA'), ('GIE', 'GIE'), ('ASSOCIATION', 'Association'), ('OTHER', 'Autre')], max_length=30, verbose_name='Forme juridique')),
                ('registration_number', models.CharField(blank=True, max_length=120, verbose_name="Numéro d'immatriculation")),
                ('tax_number', models.CharField(blank=True, max_length=120, verbose_name='Identifiant fiscal')),
                ('registered_office', models.CharField(blank=True, max_length=255, verbose_name='Siège social')),
                ('share_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Capital social')),
                ('incorporation_date', models.DateField(blank=True, null=True, verbose_name='Date de constitution')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Entité immatriculée')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('meeting_date', models.DateTimeField(verbose_name='Date et heure')),
                ('title', models.CharField(max_length=255, verbose_name='Objet de la réunion')),
                ('agenda', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('minutes', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('decisions', models.TextField(blank=True, verbose_name='Décisions')),
            ],
            options={
                'verbose_name': 'Réunion du projet',
                'verbose_name_plural': 'Réunions des projets',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('title', models.CharField(max_length=255, verbose_name='Étape')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Début prévu')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Fin prévue')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('planned_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Budget prévu')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Coût réel')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Avancement (%)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('DELAYED', 'En retard'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Étape du projet',
                'verbose_name_plural': 'Étapes des projets',
                'ordering': ['planned_end_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('revenue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du revenu')),
                ('supporting_document', models.FileField(blank=True, upload_to=community_investment.models.project_document_upload_to, verbose_name='Justificatif')),
            ],
            options={
                'verbose_name': 'Revenu du projet',
                'verbose_name_plural': 'Revenus des projets',
                'ordering': ['-revenue_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('holder_type', models.CharField(choices=[('GROUP', 'Groupement'), ('POSTE', 'La Poste Sénégal'), ('YAAYESS', 'YAAYESS'), ('PARTNER', 'Partenaire institutionnel'), ('INDIVIDUAL', 'Personne physique'), ('OTHER', 'Autre')], max_length=20, verbose_name="Type d'associé ou d'actionnaire")),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Nom ou dénomination')),
                ('shares_count', models.PositiveBigIntegerField(default=0, verbose_name='Nombre de parts ou actions')),
                ('ownership_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Participation économique (%)')),
                ('voting_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Droits de vote (%)')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposé'), ('APPROVED', 'Approuvé'), ('ACTIVE', 'Participation active'), ('SUSPENDED', 'Suspendu'), ('EXITED', 'Sorti du capital')], default='PROPOSED', max_length=20, verbose_name='Statut')),
                ('investment_agreement_reference', models.CharField(blank=True, max_length=120, verbose_name="Référence de la convention d'investissement")),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Participation approuvée le')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Associé ou actionnaire',
                'verbose_name_plural': 'Associés et actionnaires',
                'ordering': ['project', '-ownership_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ReinvestmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant réinvesti')),
                ('decision_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de décision')),
                ('resolution_reference', models.CharField(max_length=120, verbose_name='Référence de la décision')),
                ('description', models.TextField(blank=True, verbose_name='Objet du réinvestissement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('transaction_type', models.CharField(choices=[('INITIAL_SUBSCRIPTION', 'Souscription initiale'), ('CAPITAL_INCREASE', 'Augmentation de capital'), ('TRANSFER', 'Transfert'), ('REDEMPTION', 'Rachat'), ('CANCELLATION', 'Annulation'), ('ADJUSTMENT', 'Régularisation')], max_length=30, verbose_name="Type d'opération")),
                ('shares_count', models.PositiveBigIntegerField(default=0, verbose_name='Nombre de titres')),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date de l'opération")),
                ('resolution_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence de la décision')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Mouvement de parts ou actions',
                'verbose_name_plural': 'Mouvements de parts ou actions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='communityinvestmentproject',
            options={'ordering': ['-created_at'], 'permissions': [('manage_community_investments', 'Peut gérer les investissements communautaires'), ('review_community_investment', 'Peut instruire un investissement communautaire'), ('approve_community_investment', 'Peut approuver un investissement communautaire'), ('view_national_investment_dashboard', 'Peut consulter le tableau de bord national'), ('view_project_financial_data', 'Peut consulter les données financières des projets'), ('validate_project_contribution', 'Peut valider les apports aux projets'), ('approve_profit_allocation', "Peut approuver l'affectation des bénéfices")], 'verbose_name': "Projet d'investissement communautaire", 'verbose_name_plural': "Projets d'investissement communautaire"},
        ),
        migrations.RemoveConstraint(
            model_name='communityinvestmentproject',
            name='ci_project_requested_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='communityinvestmentproject',
            name='ci_project_contribution_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='communityinvestmentproject',
            name='ci_project_approved_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='communityinvestmentproject',
            name='ci_project_mobilized_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='communityinvestmentproject',
            name='ci_project_disbursed_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='investmenteligibilitypolicy',
            name='ci_policy_minimum_capital_positive',
        ),
        migrations.RemoveConstraint(
            model_name='investmenteligibilitypolicy',
            name='ci_policy_repayment_rate_valid',
        ),
        migrations.RemoveConstraint(
            model_name='investmenteligibilitypolicy',
            name='ci_policy_overdue_rate_valid',
        ),
        migrations.RemoveConstraint(
            model_name='postaloffice',
            name='ci_unique_office_name_per_region',
        ),
        migrations.RemoveField(
            model_name='communityinvestmentproject',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='communityinvestmentproject',
            name='community_contribution',
        ),
        migrations.RemoveField(
            model_name='communityinvestmentproject',
            name='disbursed_amount',
        ),
        migrations.RemoveField(
            model_name='communityinvestmentproject',
            name='mobilized_amount',
        ),
        migrations.RemoveField(
            model_name='communityinvestmentproject',
            name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='investmenteligibilitypolicy',
            name='maximum_overdue_rate',
        ),
        migrations.RemoveField(
            model_name='investmenteligibilitypolicy',
            name='minimum_repayment_rate',
        ),
        migrations.RemoveField(
            model_name='investmenteligibilitypolicy',
            name='requires_audited_accounts',
        ),
        migrations.RemoveField(
            model_name='investmenteligibilitypolicy',
            name='requires_group_approval',
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='general_assembly_resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la résolution'),
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='general_assembly_resolution_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Référence de la résolution du groupement'),
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='governance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Score de gouvernance (%)'),
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='group_planned_equity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Participation prévue du groupement'),
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='savings_regularity_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name="Régularité de l'épargne (%)"),
        ),
        migrations.AddField(
            model_name='communityinvestmentproject',
            name='total_project_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût total estimé du projet'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='minimum_governance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Score minimal de gouvernance (%)'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='minimum_group_equity_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Participation économique minimale devant rester détenue par le groupement dans le projet.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Participation minimale du groupement (%)'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='minimum_internal_reserve_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Réserve interne minimale du groupement (%)'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='minimum_savings_regularity_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name="Régularité minimale de l'épargne (%)"),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_business_plan',
            field=models.BooleanField(default=True, verbose_name="Plan d'affaires requis"),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_conflict_of_interest_declaration',
            field=models.BooleanField(default=True, verbose_name="Déclaration des conflits d'intérêts requise"),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_environmental_assessment',
            field=models.BooleanField(default=False, verbose_name='Évaluation environnementale requise'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_feasibility_study',
            field=models.BooleanField(default=True, verbose_name='Étude de faisabilité requise'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_general_assembly_resolution',
            field=models.BooleanField(default=True, verbose_name="Résolution de l'assemblée générale requise"),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_signed_investment_agreement',
            field=models.BooleanField(default=True, verbose_name="Convention d'investissement signée requise"),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='requires_verified_financial_statements',
            field=models.BooleanField(default=True, verbose_name='États financiers vérifiés requis'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='suggested_poste_equity_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text="Valeur indicative uniquement. La participation définitive doit résulter d'apports valorisés et d'une convention signée.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Participation indicative de La Poste (%)'),
        ),
        migrations.AddField(
            model_name='investmenteligibilitypolicy',
            name='suggested_yaayess_equity_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text="Valeur indicative uniquement. La participation définitive doit résulter d'apports valorisés et d'une convention signée.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Participation indicative de YAAYESS (%)'),
        ),
        migrations.AlterField(
            model_name='communityinvestmentproject',
            name='capital_at_submission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Capital du groupement à la soumission'),
        ),
        migrations.AlterField(
            model_name='communityinvestmentproject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_investment_projects', to='epargnecredit.group', verbose_name="Groupement d'épargne-crédit"),
        ),
        migrations.AlterField(
            model_name='communityinvestmentproject',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Avancement opérationnel (%)'),
        ),
        migrations.AlterField(
            model_name='communityinvestmentproject',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_community_investment_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable opérationnel'),
        ),
        migrations.AlterField(
            model_name='communityinvestmentproject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis au bureau de poste'), ('OFFICE_REVIEW', 'Examen par le bureau'), ('ADDITIONAL_INFO', 'Informations complémentaires requises'), ('REGIONAL_REVIEW', 'Examen régional'), ('CENTRAL_REVIEW', 'Instruction par la Direction des investissements'), ('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('STRUCTURING', 'Structuration'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CAPITALIZATION', 'Capital en constitution'), ('READY_TO_START', 'Prêt à démarrer'), ('IN_PROGRESS', 'En exploitation'), ('SUSPENDED', 'Suspendu'), ('COMPLETED', 'Cycle terminé'), ('CLOSED', 'Clôturé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='investmenteligibilitypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='investmenteligibilitypolicy',
            name='minimum_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000000.00'), help_text="Seuil de capitalisation permettant au groupement d'accéder à l'accompagnement. Valeur initiale : 30 000 000 FCFA.", max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capital collectif minimum'),
        ),
        migrations.AlterField(
            model_name='investmenteligibilitypolicy',
            name='minimum_group_age_months',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)], verbose_name='Ancienneté minimale du groupement en mois'),
        ),
        migrations.AlterField(
            model_name='investmenteligibilitypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='postalregion',
            name='code',
            field=models.CharField(help_text='Exemples : DKR, THS, KOL, STL.', max_length=30, unique=True, verbose_name='Code de la région'),
        ),
        migrations.AlterField(
            model_name='postalregion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='postalregion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('total_project_cost__gte', 0)), name='ci_project_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='communityinvestmentproject',
            constraint=models.CheckConstraint(condition=models.Q(('group_planned_equity__gte', 0)), name='ci_project_group_equity'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_capital__gt', 0)), name='ci_policy_capital_positive'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_group_equity_rate__gt', 0), ('minimum_group_equity_rate__lte', 100)), name='ci_policy_group_equity'),
        ),
        migrations.AddConstraint(
            model_name='investmenteligibilitypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_governance_score__gte', 0), ('minimum_governance_score__lte', 100)), name='ci_policy_governance'),
        ),
        migrations.AddConstraint(
            model_name='postaloffice',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='ci_unique_office_region'),
        ),
        migrations.AddField(
            model_name='communityimpact',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='communityimpact',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_project_impacts', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dividend_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par'),
        ),
        migrations.AddField(
            model_name='dividendentitlement',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='community_investment.dividenddeclaration', verbose_name='Déclaration'),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='community_investment.dividendentitlement', verbose_name='Droit aux dividendes'),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_dividend_payments', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='membereconomicright',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_economic_rights', to='epargnecredit.groupmember', verbose_name='Membre du groupement'),
        ),
        migrations.AddField(
            model_name='profitallocation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profit_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='dividenddeclaration',
            name='profit_allocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_declaration', to='community_investment.profitallocation', verbose_name='Affectation du résultat'),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_project_contributions', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_documents', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_project_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='projectfeeaccrual',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_fee_accruals', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='projectfeerule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_fee_rules', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par'),
        ),
        migrations.AddField(
            model_name='projectfeerule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectfeeaccrual',
            name='fee_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='community_investment.projectfeerule', verbose_name='Règle de rémunération'),
        ),
        migrations.AddField(
            model_name='projectfinancialstatement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectfinancialstatement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_project_statements', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='profitallocation',
            name='financial_statement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_allocation', to='community_investment.projectfinancialstatement', verbose_name='État financier'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_project_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par'),
        ),
        migrations.AddField(
            model_name='projectlegalentity',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectmeeting',
            name='organized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_project_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Organisée par'),
        ),
        migrations.AddField(
            model_name='projectmeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='community_investment_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='projectmeeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_project_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectrevenue',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_project_revenues', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='projectstakeholder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par'),
        ),
        migrations.AddField(
            model_name='projectstakeholder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_stakeholdings', to='epargnecredit.group', verbose_name='Groupement'),
        ),
        migrations.AddField(
            model_name='projectstakeholder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projectstakeholder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_stakeholdings', to=settings.AUTH_USER_MODEL, verbose_name='Personne physique'),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='community_investment.projectstakeholder', verbose_name='Associé ou actionnaire'),
        ),
        migrations.AddField(
            model_name='membereconomicright',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_economic_rights', to='community_investment.projectstakeholder', verbose_name='Participation du groupement'),
        ),
        migrations.AddField(
            model_name='dividendentitlement',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_entitlements', to='community_investment.projectstakeholder', verbose_name='Associé ou actionnaire'),
        ),
        migrations.AddField(
            model_name='reinvestmentdecision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reinvestments', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='reinvestmentdecision',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_reinvestments', to='community_investment.communityinvestmentproject', verbose_name='Projet destinataire'),
        ),
        migrations.AddField(
            model_name='reinvestmentdecision',
            name='source_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_reinvestments', to='community_investment.communityinvestmentproject', verbose_name='Projet source'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_share_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='from_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_share_transactions', to='community_investment.projectstakeholder', verbose_name='Cédant'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='community_investment.communityinvestmentproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='sharetransaction',
            name='to_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_share_transactions', to='community_investment.projectstakeholder', verbose_name='Bénéficiaire'),
        ),
        migrations.AddConstraint(
            model_name='projectfeeaccrual',
            constraint=models.UniqueConstraint(fields=('fee_rule', 'period_start', 'period_end'), name='ci_unique_fee_period'),
        ),
        migrations.AddConstraint(
            model_name='projectfinancialstatement',
            constraint=models.UniqueConstraint(fields=('project', 'period_start', 'period_end'), name='ci_unique_statement_period'),
        ),
        migrations.AddIndex(
            model_name='projectstakeholder',
            index=models.Index(fields=['project', 'holder_type', 'status'], name='ci_holder_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstakeholder',
            constraint=models.UniqueConstraint(condition=models.Q(('holder_type__in', ['GROUP', 'POSTE', 'YAAYESS'])), fields=('project', 'holder_type'), name='ci_unique_core_holder'),
        ),
        migrations.AddConstraint(
            model_name='projectstakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_percentage__gte', 0), ('ownership_percentage__lte', 100)), name='ci_holder_ownership_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectstakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('voting_percentage__gte', 0), ('voting_percentage__lte', 100)), name='ci_holder_voting_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('declared_value__gte', 0)), name='ci_contribution_declared'),
        ),
        migrations.AddConstraint(
            model_name='projectcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('recognized_value__gte', 0)), name='ci_contribution_recognized'),
        ),
        migrations.AddConstraint(
            model_name='membereconomicright',
            constraint=models.UniqueConstraint(fields=('stakeholder', 'member'), name='ci_unique_member_right'),
        ),
        migrations.AddConstraint(
            model_name='dividendentitlement',
            constraint=models.UniqueConstraint(fields=('declaration', 'stakeholder'), name='ci_unique_dividend_holder'),
        ),
    ]
